// <auto-generated />
using System;
using APIGenerationProject.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIGenerationProject.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20251031200541_Second init1")]
    partial class Secondinit1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIGenerationProject.Repository.Model.Catogery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Catogeries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 31, 20, 5, 41, 117, DateTimeKind.Utc).AddTicks(9892),
                            CreatedBy = "System",
                            Description = "Devices and gadgets",
                            Name = "Electronics",
                            ProductId = 0,
                            UpdatedAt = new DateTime(2025, 10, 31, 20, 5, 41, 117, DateTimeKind.Utc).AddTicks(9895),
                            UpdatedBy = "System",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 31, 20, 5, 41, 117, DateTimeKind.Utc).AddTicks(9897),
                            CreatedBy = "System",
                            Description = "Men and Women Clothes",
                            Name = "Clothes",
                            ProductId = 0,
                            UpdatedAt = new DateTime(2025, 10, 31, 20, 5, 41, 117, DateTimeKind.Utc).AddTicks(9898),
                            UpdatedBy = "System",
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("APIGenerationProject.Repository.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CatogeryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CatogeryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CatogeryId = 1,
                            CreatedAt = new DateTime(2025, 10, 31, 20, 5, 41, 118, DateTimeKind.Utc).AddTicks(7),
                            CreatedBy = "System",
                            Description = "Gaming Laptop",
                            Name = "Laptop",
                            Price = 25000m,
                            Stock = 5,
                            UpdatedAt = new DateTime(2025, 10, 31, 20, 5, 41, 118, DateTimeKind.Utc).AddTicks(7),
                            UpdatedBy = "System",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CatogeryId = 2,
                            CreatedAt = new DateTime(2025, 10, 31, 20, 5, 41, 118, DateTimeKind.Utc).AddTicks(13),
                            CreatedBy = "System",
                            Description = "Cotton T-Shirt",
                            Name = "T-Shirt",
                            Price = 250m,
                            Stock = 50,
                            UpdatedAt = new DateTime(2025, 10, 31, 20, 5, 41, 118, DateTimeKind.Utc).AddTicks(14),
                            UpdatedBy = "System",
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("APIGenerationProject.Repository.Model.Product", b =>
                {
                    b.HasOne("APIGenerationProject.Repository.Model.Catogery", "Catogery")
                        .WithMany("Products")
                        .HasForeignKey("CatogeryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catogery");
                });

            modelBuilder.Entity("APIGenerationProject.Repository.Model.Catogery", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
