// <auto-generated />
using System;
using APIGenerationProject.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIGenerationProject.Migrations
{
    [DbContext(typeof(ProjectContext))]
    partial class ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIGenerationProject.Repository.Model.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Carts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 1, 7, 56, 15, 757, DateTimeKind.Utc).AddTicks(1739),
                            CreatedBy = "System",
                            UpdatedAt = new DateTime(2025, 11, 1, 7, 56, 15, 757, DateTimeKind.Utc).AddTicks(1740),
                            UpdatedBy = "System",
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("APIGenerationProject.Repository.Model.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CartId = 1,
                            CreatedAt = new DateTime(2025, 11, 1, 7, 56, 15, 757, DateTimeKind.Utc).AddTicks(1774),
                            CreatedBy = "System",
                            ProductId = 2,
                            Quantity = 2,
                            UnitPrice = 300m,
                            UpdatedAt = new DateTime(2025, 11, 1, 7, 56, 15, 757, DateTimeKind.Utc).AddTicks(1775),
                            UpdatedBy = "System",
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("APIGenerationProject.Repository.Model.Catogery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Catogeries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 1, 7, 56, 15, 757, DateTimeKind.Utc).AddTicks(1149),
                            CreatedBy = "System",
                            Description = "Devices and gadgets",
                            Name = "Electronics",
                            ProductId = 0,
                            UpdatedAt = new DateTime(2025, 11, 1, 7, 56, 15, 757, DateTimeKind.Utc).AddTicks(1154),
                            UpdatedBy = "System",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 1, 7, 56, 15, 757, DateTimeKind.Utc).AddTicks(1162),
                            CreatedBy = "System",
                            Description = "Men and Women Clothes",
                            Name = "Clothes",
                            ProductId = 0,
                            UpdatedAt = new DateTime(2025, 11, 1, 7, 56, 15, 757, DateTimeKind.Utc).AddTicks(1162),
                            UpdatedBy = "System",
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("APIGenerationProject.Repository.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 1, 7, 56, 15, 757, DateTimeKind.Utc).AddTicks(1633),
                            CreatedBy = "System",
                            OrderDate = new DateTime(2025, 11, 1, 9, 56, 15, 757, DateTimeKind.Local).AddTicks(1637),
                            TotalAmount = 25250m,
                            UpdatedAt = new DateTime(2025, 11, 1, 7, 56, 15, 757, DateTimeKind.Utc).AddTicks(1633),
                            UpdatedBy = "System",
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("APIGenerationProject.Repository.Model.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 1, 7, 56, 15, 757, DateTimeKind.Utc).AddTicks(1689),
                            CreatedBy = "System",
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 25000m,
                            UpdatedAt = new DateTime(2025, 11, 1, 7, 56, 15, 757, DateTimeKind.Utc).AddTicks(1690),
                            UpdatedBy = "System",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 1, 7, 56, 15, 757, DateTimeKind.Utc).AddTicks(1695),
                            CreatedBy = "System",
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 250m,
                            UpdatedAt = new DateTime(2025, 11, 1, 7, 56, 15, 757, DateTimeKind.Utc).AddTicks(1695),
                            UpdatedBy = "System",
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("APIGenerationProject.Repository.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CatogeryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CatogeryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CatogeryId = 1,
                            CreatedAt = new DateTime(2025, 11, 1, 7, 56, 15, 757, DateTimeKind.Utc).AddTicks(1493),
                            CreatedBy = "System",
                            Description = "Gaming Laptop",
                            Name = "Laptop",
                            Price = 25000m,
                            Stock = 5,
                            UpdatedAt = new DateTime(2025, 11, 1, 7, 56, 15, 757, DateTimeKind.Utc).AddTicks(1494),
                            UpdatedBy = "System",
                            isDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            CatogeryId = 2,
                            CreatedAt = new DateTime(2025, 11, 1, 7, 56, 15, 757, DateTimeKind.Utc).AddTicks(1504),
                            CreatedBy = "System",
                            Description = "Cotton T-Shirt",
                            Name = "T-Shirt",
                            Price = 250m,
                            Stock = 50,
                            UpdatedAt = new DateTime(2025, 11, 1, 7, 56, 15, 757, DateTimeKind.Utc).AddTicks(1505),
                            UpdatedBy = "System",
                            isDeleted = false
                        });
                });

            modelBuilder.Entity("APIGenerationProject.Repository.Model.CartItem", b =>
                {
                    b.HasOne("APIGenerationProject.Repository.Model.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIGenerationProject.Repository.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("APIGenerationProject.Repository.Model.OrderItem", b =>
                {
                    b.HasOne("APIGenerationProject.Repository.Model.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APIGenerationProject.Repository.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("APIGenerationProject.Repository.Model.Product", b =>
                {
                    b.HasOne("APIGenerationProject.Repository.Model.Catogery", "Catogery")
                        .WithMany("Products")
                        .HasForeignKey("CatogeryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Catogery");
                });

            modelBuilder.Entity("APIGenerationProject.Repository.Model.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("APIGenerationProject.Repository.Model.Catogery", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("APIGenerationProject.Repository.Model.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
